### ISSUE TITLE
Cant go get the gokit plugin

### ISSUE THREAD

**Issue by joeblew99** [goadesign/plugins#1]
steps to repo:

````
# goa v2
go get -u goa.design/goa
cd /Users/apple/workspace/go/src/goa.design/goa/cmd/goa && go install

goa version
goa version v2.0.0-wip

# now try gokit plugin.
go get -u goa.design/plugins/goakit
package goa.design/plugins/goakit: unrecognized import path "goa.design/plugins/goakit" (parsing goa.design/plugins/goakit: XML syntax error on line 48: expected element name after <)

````

**Comment by joeblew99** [comment]
Fixed it. just needed pathing a bit different.
Maybe update the readme for everyone..


dep:

	# goa v2
	go get -u ${EX_GO_PATH}/...
	cd ${EX_FILE_PATH}/cmd/goa && go install

dep-gen:

	# check goa tools are there
	goa version

	# now try gokit plugin.

	go get -u goa.design/plugins/...

	goa gen goa.design/plugins/goakit/examples/cellar/design

**Comment by kumarsiva07** [comment]
I am using dep for vendor management
```
dep init
unable to deduce repository and source type for "goa.design/plugins/goakit": unable to read metadata: unable to parse go-import metadata: XML syntax error on line 48: expected element name after <
```
Still i'm getting error

**Comment by raphael** [comment]
doing `go get goa.design/plugins/...` works,  `go get goa.design/plugins/goakit` should work too though.

**Comment by raphael** [comment]
This is now fixed.
