### ISSUE TITLE
Question/Feature: CORS does not work for GOA generated grpc servers

### ISSUE THREAD

**Issue by ghoben** [goadesign/plugins#100]
CORS does not work for GOA generated grpc servers.

I'm trying to use the goa generated server as a backend for the grpc-web framework. Since the grpc-web framework issues calls from the browser I'm running into problem that I need CORS on the grpc server. Since the CORS plugin adds the handler to the http server I was expecting that this is also done for the grpc server. Any change this features get's implemented?

**Comment by raphael** [comment]
I'd be happy to merge a PR that would add this functionality!
