### ISSUE TITLE
Docs plugin - incomplete result for mixed one-off and streaming payload

### ISSUE THREAD

**Issue by dvictor** [goadesign/plugins#101]
If a method accepts both one-off and streaming payloads, the docs plugin only represents the one-off payload.

Example:
```
	Method("myMethod", func() {
		Payload(func() {
			...
		})

		StreamingPayload(func() {
			...
		})
```

In docs.json only Payload will be represented.

**Comment by raphael** [comment]
This is fixed by https://github.com/goadesign/plugins/pull/104 and https://github.com/goadesign/plugins/pull/106
