### ISSUE TITLE
[docs] content keeps getting appended if a different output directory is specified

### ISSUE THREAD

**Issue by arangamani** [goadesign/plugins#108]
If the output directory is customized, the content to `gen/docs.json` keeps getting appended every time the code is generated.

I see we have this code [here](https://github.com/goadesign/plugins/blob/v3/docs/generate.go#L37-L46) that attempts to delete the `gen/docs.json` file before generating it again but it only works if the output directory is not customized (the default is the current directory).

**Comment by raphael** [comment]
This is a current known limitation, the plugin does not have access to the custom location and changing the interface with Goa would be a breaking change. There might be "less-than-elegant" ways to tackle this issue, e.g. by having Goa define an environment variable that contains the path that plugins can leverage, a bit on the fence as to whether this is worth it... At the very least though that limitation should be documented, I'll add that to the README.
