### ISSUE TITLE
How to write custom security plugin?

### ISSUE THREAD

**Issue by kumarsiva07** [goadesign/plugins#11]
Can you provide template to write a custom security plugin?

I have authentication service. So I need to take cookie and connect to that service to find the user and also need to keep that user in context. Then only i can access the user inside app logic.

**Comment by nitinmohan87** [comment]
@kumarsiva07 Very sorry for the delayed response. We were in the midst of making some refactors to the security plugin. In the latest security plugin, we generate auth functions for each security scheme which the users can implement with their own preferred logic (can also provide custom function that match the auth function type). [Calc example](https://github.com/goadesign/plugins/tree/master/security/examples/calc) provides an example to implement these functions.

Let me make sure I understand your use case correctly. Is the "authentication service" you refer to built with goa v2?

Let's say you are using `APIKeySecurity` for the endpoint. You could provide a custom auth function which returns a function of type [AuthorizeAPIKeyFunc](https://github.com/goadesign/plugins/blob/56b0a49feb736b3dfd52112110d5fbf07a58fba7/security/scheme.go#L67)
```
func YourCustomAPIKeyFn(keyStore <Store>) security.AuthorizeAPIKeyFunc {
  return security.AuthorizeAPIKeyFunc(func(ctx context.Context, key string, s *APIKeyScheme) (context.Context, error) {
    // Get user from "keyStore" using "key"
    ctx = ctx.WithValue("user", user)
  })
}
```
Then in the server `main.go`, you can pass this custom function to the secure endpoint as follows
```
keyStore := <intialize key store>
svcEndpoints = svc.NewSecureEndpoints(svcSvc, YourCustomAPIKeyFn(keystore))
```
Hope this helps!
