### ISSUE TITLE
Request RemoteAddr

### ISSUE THREAD

**Issue by tpoxa** [goadesign/plugins#14]
Hi, I am trying to migrate from goa.design v1 to v2 version.

I am stacked with RemoteAddr. I do need to with client IP address in my HTTP service. Any workaround how do this properly with v2?  Thank you. 

BTW, @raphael @nitinmohan87 do you have any public slack channel to discuss such questions?

**Comment by raphael** [comment]
Hello, you can ask these questions in the [goa slack channel](https://gophers.slack.com/messages/goa/) (sign up [here](https://gophersinvite.herokuapp.com/)). Also note that this repo is the plugins repo and not the main [goa repo](https://github.com/goadesign/goa).

To answer the question, you can mount middlewares on the HTTP handler that will set the remote address in the context for example where the debugging middleware is mounted in the default `main` (https://github.com/goadesign/goa/blob/v2/examples/calc/cmd/calcsvc/main.go#L93-L101)
