### ISSUE TITLE
OTEL plugin not working

### ISSUE THREAD

**Issue by abice** [goadesign/plugins#156]
I've just started looking at GOA for some API definition creation, and came across the OTEL plugin (we're currently looking at possibly migrating over to OTEL for our projects).

Turns out the otel plugin string matches against `{{- range Routes }}` when the template has `{{- range .Routes }}` instead. (the `.` is missing).

This is actually only the first issue that prevents the plugin from working.  The second problem is that the location of the replacement does not have the `.Path` variable to use (.Path looks to be under the .Routes information, and would require to be under the range portion of the template, giving you something that looks like this.  

```go
s.Source = strings.Replace(
  s.Source,
  `mux.Handle("{{ .Verb }}", "{{ .Path }}", f)`,
  `mux.Handle("{{ .Verb }}", "{{ .Path }}", otelhttp.WithRouteTag("{{ .Path }}", f).ServeHTTP)`,
  1,
)
```

I'm not overly familiar with otel mappings, otherwise I would open a PR myself and offer up a solution, but this is my first foray into goa, plugins, and otel, so I _think_ this is what was expected to happen.

So far I've been enjoying learning about GOA and hope that it can fit our needs.  Thanks for creating/supporting it!

**Comment by raphael** [comment]
Thank you for the note, the plugin needed additional work. https://github.com/goadesign/plugins/pull/155 fixes it!
