### ISSUE TITLE
security plugin must be imported before goakit plugin

### ISSUE THREAD

**Issue by nicholaslam** [goadesign/plugins#32]
I’m getting an error when using the goakit plugin with the security plugin. The goakit plugin makes the generated code use go-kit’s `endpoint.Endpoint` instead of goa’s `goa.endpoint`, but `endpoint.Endpoint` is not compatible with the `goa.Endpoint`.

I was able to workaround this issue by importing `goa.design/plugins/security` package before `goa.design/plugins/goakit`.
```go
package design

import "goa.design/goa/http/design"
import "goa.design/plugins/security/dsl"
import _ "goa.design/plugins/security" // Needs to be imported before goakit
import _ "goa.design/plugins/goakit" 
```

To reproduce the issue, in your design import the goakit plugin before the security plugin and secure a method.

**Comment by nitinmohan87** [comment]
Thanks for reporting this issue. It should be fixed in latest plugins and goa v2.
