### ISSUE TITLE
Need to specify name:attribute of token in header when using JWT auth

### ISSUE THREAD

**Issue by nicholaslam** [goadesign/plugins#33]
I'm consistently getting the following response ("missing required payload") when I try to send a JWT via the Authorization header:
```
{
    "token": "blahblahblah",
    "detail": "missing required payload",
    "temporary": false,
    "timeout": false
}
```

The workaround is to include `dsl.Header("token:Authorization")` in the design for the method:
```go
package design

import "goa.design/goa/http/design"
import "goa.design/plugins/security/dsl"
import _ "goa.design/plugins/security"

...

var _ = dsl.Service("foobar", func() {

...

	dsl.Method("secure", func() {
		dsl.Description("This action is secured with the jwt scheme")
		dsl.Security(JWTAuth, func() {
			dsl.Scope("api:read")
		})
		dsl.Payload(func() {
			dsl.Token("token", design.String, func() {
				dsl.Description("JWT used for authentication")
			})
		})
		dsl.Result(design.String, func() {
			dsl.Example("JWT secured data")
		})
		dsl.HTTP(func() {
			dsl.GET("/secure")
			dsl.Header("token:Authorization")
			dsl.Response(design.StatusOK)
		})
	})

...
```

**Comment by nicholaslam** [comment]
I was also unable to use the "Bearer" prefix. I had to manually strip the “Bearer” prefix in my JWT validation function.

**Comment by nitinmohan87** [comment]
@nicholaslam Thanks for reporting the issue.
It seems there is a bug in goa v2 that requires an empty payload to be sent even though the JWT token is provided via an Authorization header. So without doing your workaround, if you pass an empty payload and the JWT token in Authorization header it works as expected.
But I am not able to reproduce the issue that you mention in the comment (manually trimming Bearer prefix from the token). Here is my design
```
var JWT = JWTSecurity("JWT", func() {
  Scope("api:read", "Read access")
})

var _ = Service("dummy", func() {
  Method("index", func() {
    Security(JWT, func() {
      Scope("api:read")
    })
    Payload(func() {
      Attribute("id", String)
      Token("token", String)
    })
    HTTP(func() {
      GET("/{id}")
      Response(StatusOK)
    })
  })
})

# My implementation of "index" endpoint where I just print the JWT token in the logs
// Index returns the list of actions in the project.
func (s *dummySvc) Index(ctx context.Context, p *dummysvc.IndexPayload) error {
  s.logger.Print(*p.Token)
  return nil
}
```
Here is the server logs for my curl request
```
curl -H "Authorization: Bearer my_jwt_token" -X GET http://localhost:8080/1 -d '{}'

# Server logs
[dummy] 10:29:26  id=Nf960fwW req=GET /1 from=127.0.0.1
[dummy] 10:29:26 my_jwt_token
[dummy] 10:29:26  id=Nf960fwW status=200 bytes=0 time=387.953µs
```
As you can see, the "Bearer" prefix is trimmed by the plugin itself.

**Comment by nicholaslam** [comment]
@nitinmohan87 Thank you for your response! Unfortunately, I was unable to get it to work with your design. I forgot to mention I am using the goakit plugin with the security plugin. Using the design above it was looking for the token in the payload/body and ignoring the header.

**Comment by nicholaslam** [comment]
@nitinmohan87 I think i figured it out. I was not using the secure decoder.
