### ISSUE TITLE
No security attribute on method generates invalid code. 

### ISSUE THREAD

**Issue by zsxawerdu** [goadesign/plugins#7]
https://github.com/goadesign/plugins/blob/6127466225ad03c6db8b215094b49a72d09f9933/security/generate.go#L169

If a method has no DSL Security Attribute example Security(....)  then it fails on build of generated project with "undefined: NewMethodName"  

Changing the above line to this 
```
{{ .FieldName }}: {{ .VarName }}{{ if not .Requirements}}Endpoint{{ end }}{{ if .Requirements }}({{ .NonSecureVarName }}{{ end }}(s){{ if .Requirements }}){{ end }},```
```

It seems to fix the issue, compiles and  method is *seems* to execute correctly.  However there is probably easier way to fix this.

**Comment by tpoxa** [comment]
Same problem, unable to mix unsecured and secured methods

**Comment by tpoxa** [comment]
@zsxawerdu can you make pull request please?

**Comment by nitinmohan87** [comment]
Sorry for the delay. Thanks a lot for reporting this issue. I have fixed it in the PR above (still under dev).
