### ISSUE TITLE
Unable to get goakit plugin v2

### ISSUE THREAD

**Issue by uruemu** [goadesign/plugins#77]
When running the following command on the terminal, I get a bunch of errors. See the command and output below;
**Command**
`go get -u goa.design/goa/... && go get -u goa.design/plugins/goakit/...`
**Output**
`package goa.design/goa/v3/codegen: cannot find package "goa.design/goa/v3/codegen" in any of:
        /usr/local/Cellar/go@1.10/1.10.8/libexec/go/src/goa.design/goa/v3/codegen (from $GOROOT)
        /Users/uga/go/src/goa.design/goa/v3/codegen (from $GOPATH)
package goa.design/goa/v3/eval: cannot find package "goa.design/goa/v3/eval" in any of:
        /usr/local/Cellar/go@1.10/1.10.8/libexec/go/src/goa.design/goa/v3/eval (from $GOROOT)
        /Users/uga/go/src/goa.design/goa/v3/eval (from $GOPATH)
package goa.design/goa/v3/expr: cannot find package "goa.design/goa/v3/expr" in any of:
        /usr/local/Cellar/go@1.10/1.10.8/libexec/go/src/goa.design/goa/v3/expr (from $GOROOT)
        /Users/uga/go/src/goa.design/goa/v3/expr (from $GOPATH)
package goa.design/goa/v3/http/codegen: cannot find package "goa.design/goa/v3/http/codegen" in any of:
        /usr/local/Cellar/go@1.10/1.10.8/libexec/go/src/goa.design/goa/v3/http/codegen (from $GOROOT)
        /Users/uga/go/src/goa.design/goa/v3/http/codegen (from $GOPATH)
package goa.design/goa/v3/http: cannot find package "goa.design/goa/v3/http" in any of:
        /usr/local/Cellar/go@1.10/1.10.8/libexec/go/src/goa.design/goa/v3/http (from $GOROOT)
        /Users/uga/go/src/goa.design/goa/v3/http (from $GOPATH)
package goa.design/goa/v3/http/middleware: cannot find package "goa.design/goa/v3/http/middleware" in any of:
        /usr/local/Cellar/go@1.10/1.10.8/libexec/go/src/goa.design/goa/v3/http/middleware (from $GOROOT)
        /Users/uga/go/src/goa.design/goa/v3/http/middleware (from $GOPATH)
package goa.design/goa/v3/middleware: cannot find package "goa.design/goa/v3/middleware" in any of:
        /usr/local/Cellar/go@1.10/1.10.8/libexec/go/src/goa.design/goa/v3/middleware (from $GOROOT)
        /Users/uga/go/src/goa.design/goa/v3/middleware (from $GOPATH)
package goa.design/goa/v3/pkg: cannot find package "goa.design/goa/v3/pkg" in any of:
        /usr/local/Cellar/go@1.10/1.10.8/libexec/go/src/goa.design/goa/v3/pkg (from $GOROOT)
        /Users/uga/go/src/goa.design/goa/v3/pkg (from $GOPATH)
package goa.design/goa/v3/dsl: cannot find package "goa.design/goa/v3/dsl" in any of:
        /usr/local/Cellar/go@1.10/1.10.8/libexec/go/src/goa.design/goa/v3/dsl (from $GOROOT)
        /Users/uga/go/src/goa.design/goa/v3/dsl (from $GOPATH)`

My service was built in and is still running goa V2 but it seems that the plugin is trying to fetch version 3 (V3) of plugins.

Any help would be appreciated. Please keep in mind, I am a beginner in go.

**Comment by raphael** [comment]
Hello @StefanUA the problem might be that the default branches for these repo are now `v3` so you need to either clone them and then checkout the `v2` branch or (better in the long run) setup vendoring using e.g. https://github.com/golang/dep.
