### ISSUE TITLE
CORS missing endpoint.

### ISSUE THREAD

**Issue by derbexuk** [goadesign/plugins#88]
A change after goa 3.09 has introduced a bug into the generated CORS code which prevents servers from compiling or running.

This seems to be the change, in http/service/server/server.go \:

```
-// Code generated by goa v3.0.9, DO NOT EDIT.
+// Code generated by goa v3.1.1, DO NOT EDIT.
-               CORS:     NewCORSHandler(),
+               CORS:     NewCORSHandler(e.CORS, mux, decoder, encoder, errhandler, formatter),

```
I use a blanket CORS definition inside the API definition.

**Comment by raphael** [comment]
Just making sure: is this using `v3.1.1` of the `goa.design/plugins/v3` package as well? there was indeed a change but as far as I can tell `v3.1.1` of the plugin package has the updated code that should match with the latest Goa. If that's not the problem then can you please provide a simple design that reproduces the issue? thank you!

**Comment by derbexuk** [comment]
I'm sorry to waste your time Raphael, the versions didn't match, I was pretty sure that I had updated both, obviously not.
