### ISSUE TITLE
CORS: need to set `Vary: Origin` header when we use `cors.Origin('*')`

### ISSUE THREAD

**Issue by kitagry** [goadesign/plugins#95]
Hi @raphael , Thank you for the nice plugins.

Currently, if we set `cors.Origin('*')`, the plugin will set the request's `Origin` header (eg `example.com`) to `Access-Control-Allow-Origin` response header. This is not mistake, but it also need to set `Vary: Origin` response header.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Access-Control-Allow-Origin

> If the server specifies a single origin (that may dynamically change based on the requesting origin as part of a white-list) rather than the "*" wildcard, then the server should also include Origin in the Vary response header to indicate to clients that server responses will differ based on the value of the Origin request header.

But, CORS plugin doesn't set `Vary: Origin` response header, when we set `cors.Origin('*')`. 

https://github.com/goadesign/plugins/blob/v3/cors/generate.go#L206-L208

Thank you.

<details><summary>How to reproduce</summary>

`design.go`:

```go
package design

import (
	. "goa.design/goa/v3/dsl"
	cors "goa.design/plugins/v3/cors/dsl"
)

var _ = Service("calc", func() {
	Description("The calc service exposes public endpoints that defines CORS policy.")
	// Add CORS policy using the CORS DSLs
	cors.Origin("*", func() {
		cors.Credentials()
	})

	Method("test", func() {
		Result(Int)
		HTTP(func() {
			GET("/test")
			Response(StatusOK)
		})
	})
})
```

and then, run application.

```bash
$ curl http://localhost:8080/test -H 'Origin: example.com' -i
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: example.com
Content-Type: application/json
Date: Tue, 08 Dec 2020 01:17:45 GMT
Content-Length: 2

0
```
</details>

**Comment by raphael** [comment]
That makes sense, good catch! happy to merge a PR that removes the check.

**Comment by kitagry** [comment]
Thank you for the review!
